// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FinalchangingforORMdataannotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalchangingforORMdataannotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201609181145136_Final-changing-for-ORM-data-annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
