// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Date31082016time0912 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Date31082016time0912));
        
        string IMigrationMetadata.Id
        {
            get { return "201608310613043_Date-31-08-2016-time-09-12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
