// <auto-generated />
namespace ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Date04092016time1842 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Date04092016time1842));
        
        string IMigrationMetadata.Id
        {
            get { return "201609041543128_Date-04-09-2016-time-18-42"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
